### ISSUE TITLE
Holes for mockup

### ISSUE THREAD

**Issue by ssavickiy** [Annex-Engineering/Sherpa_Mini-Extruder#20]
Hello. I am developing a direct extruder on UltiSteel, but a new mockup cad rc1/beta3 without a pair of lower tightening holes for the screws. My design implies mounting through them on the hotend. These holes will remain in the new release of the stl? And is it possible to add them for mockup cad ?
![image](https://user-images.githubusercontent.com/23532871/105905230-3db80200-6033-11eb-9cff-6241619c2d30.png)

**Comment by Annex-Engineering** [comment]
[https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/commit/74c01825e37052597802892bef388b0dc6423901](url)
