### ISSUE TITLE
VORON0 Retention block missing

### ISSUE THREAD

**Issue by mrvanes** [Annex-Engineering/Sherpa_Mini-Extruder#27]
The retention block STL is missing in Edward Yeeks VORON0 toolhead.

**Comment by oldfar-t** [comment]
It looks like the file was deleted from the v0 Github in april, you can still dig it up through Github search but I've also attached it. It would be nice if it could be put in the STLs folder though.
[[a]_Belt_Retention_Block_x1.zip](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/files/7125615/a._Belt_Retention_Block_x1.zip)
