### ISSUE TITLE
version with 4.6 inserts

### ISSUE THREAD

**Issue by iamkarlson** [Annex-Engineering/Sherpa_Mini-Extruder#33]
Is there any technical limitation on why 4.6 mm inserts cannot be used? they seem to be super popular in the Netherlands/Germany and 5mm is almost only can be bought from Chinese shops.

**Comment by dan-and** [comment]
Well, there is a 4.6 User-Mod at https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/tree/8163d3f125bbe51e7492368310ab6a8a0761f063/User_Mods which was moved to a new repo with the last commit here. 
Maybe check that out or have a look at the sherpa micro project, which may looks like the successor of the sherpa mini.

**Comment by PapeJelly** [comment]
Looks like iamkarlson's request has been fulfilled. Therefore i will close this issue.
