### ISSUE TITLE
Normal cad file

### ISSUE THREAD

**Issue by pasha4ur** [Annex-Engineering/Sherpa_Mini-Extruder#37]
Hello

Why don't you share stp or other editable file format as Salfin, Orbiter, Vz-HextrudORT, etc?

Edrawings can't be imported in solidworks and other apps. It says about unsupported format.

**Comment by anlin93** [comment]
Cad files for R2 will be released when it reaches final release status. As always, this information is available on the Annex Discord server. Cad files for R1 are available here: https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/tree/87c5b7f5262ed1ce753bf90fcbf62043f1d25eba/CAD
