### ISSUE TITLE
Sherpa Klipper Config

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [Annex-Engineering/Sherpa_Mini-Extruder#38]
Hello there, so I have seen links online to this here but sadly someone decided to delete it.
https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/blob/master/Klipper_Config_Block.txt

Now will there be a klipper config for it or does the whole world need to reinvent the wheel (every person needs to find it out)

**Comment by anlin93** [comment]
The Klipper config block can be found here:
https://github.com/Annex-Engineering/ANNEX-Printer-Firmware/tree/main/Klipper_and_Klipper_Derivatives/Sherpa_Mini
