### ISSUE TITLE
Little questions about print settings

### ISSUE THREAD

**Issue by celtare21** [Annex-Engineering/Sherpa_Mini-Extruder#39]
So in the print settings it states as follows:

> Layer Height: 0.25mm
> Extrusion Width: Forced 0.5mm
> Infill Percentage: 40% minimum (at 0.8mm Width)
> Infill Type: Grid, Gyroid, Honeycomb, Triangle or Cubic
> Wall Count: 3 minimum (at 0.5mm Width)
> Solid Top/Bottom Layers: 4 minimum (at 0.5mm Height)

Does that mean that the extrusion width for infill is 0.8 like this?
![image](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/assets/29823626/b547bcf3-ecda-412e-8a40-22414faf6c31)

And what does 4 top/bottom laters at 0.5mm **Height** mean more exactly?

Thank you

**Comment by ChaosBlades** [comment]
Those settings are for 0.5mm nozzles. Most people have 0.4mm which is after those settings. Don't know why those settings are even listed to be honest. Does not even apply to 99.9% of people. Don't even think that is an exaggeration.

If you have printed Voron parts at Voron recommended settings then you can print this at those same settings. Plenty of guides and information online on how to do that.

**Comment by celtare21** [comment]
> Those settings are for 0.5mm nozzles. Most people have 0.4mm which is after those settings. Don't know why those settings are even listed to be honest. Does not even apply to 99.9% of people. Don't even think that is an exaggeration.
> 
> If you have printed Voron parts at Voron recommended settings then you can print this at those same settings. Plenty of guides and information online on how to do that.

I actually have a 0.5 mm nozzle 😅.
The bozzle comes standard with 0.5

**Comment by ChaosBlades** [comment]
What printer comes standard with 0.5mm? I have literally never heard of anyone using a 0.5mm nozzle. 0.6, 0.8, and even a 1.2mm nozzle but never 0.5mm.

I just looked through every printer profile OrcaSlicer offers and only the Ender 5 Pro and the two VZBots even have profiles for 0.5mm. Which none of those come standard with them.

**Comment by celtare21** [comment]
> What printer comes standard with 0.5mm? I have literally never heard of anyone using a 0.5mm nozzle. 0.6, 0.8, and even a 1.2mm nozzle but never 0.5mm.
> 
> I just looked through every printer profile OrcaSlicer offers and only the Ender 5 Pro and the two VZBots even have profiles for 0.5mm. Which none of those come standard with them.

None come "standard". I have a fully custom printer, everything was replaced and or modified. I make my own slicer profiles and this is the nozzle I'm using https://northprint3d.ca/product/tungsten-carbide-nozzle-high-flow/

**Comment by anlin93** [comment]
Sorry, somehow this issue slipped through the cracks and I only got a notification for it now. The print settings file will probably be removed at some point as the relevant information can be found in the build manual. For now I've updated the print settings file to match our current recommendations.
