### ISSUE TITLE
Release 2 Idler Arm Long collides with idler gear teeth

### ISSUE THREAD

**Issue by ChaosBlades** [Annex-Engineering/Sherpa_Mini-Extruder#41]
The idler gear teeth hit the long idler arm but not the short. Could be something slightly tweaked on the long version of the arm. Can't tell if there is anything different about them due to https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/issues/40 or if it is a print issue. It does spin free if I put the gear in backwards. The tolerances on both due seem unnecessarily tight.

In CAD the Idler gear is 9.46mm in diameter and mine is 9.54mm and the CAD model gears has 0.25mm of clearance with the arm.

**Comment by anlin93** [comment]
Please only use GitHub Issues for repo and file related problems. For general design related questions and technical support please visit our Discord server. That being said both idler arm variants have identical gear clearances, so this is most likely a print issue.
